### ISSUE TITLE
Minutes in timestamp of signature are wrong

### ISSUE THREAD

**Issue by judithmerkel** [baloise/digital-signature#90] opened 2022-02-22 13:18 UTC
Hi! 
we've noticed that the displayed minutes for each signature in our system are not correct. For every signature there is the correct hour but for the minutes it's everytime just ":09". Is there any way to fix this? 
We are currently using Confluence Server in Version 7.3.3 - if this has any impact
![digisignature](https://user-images.githubusercontent.com/100208411/155140122-bc73b3a1-edef-4996-9f59-d590980ad754.PNG)
.
thanks in advance and best wishes!
Judith

**Comment by Tiliavir** [comment] 2022-02-23 06:08
Hi @judithmerkel 

Thank you very much for reporting this behaviour - I will try to reproduce that.

Best regards
Markus

**Comment by culmat** [comment] 2022-03-10 09:23
The macro sets the signature time to the system time from the java virtual machine, see

https://github.com/baloise/digital-signature/blob/a8e98859b920ef033a0ef4a175c8fa145d756f81/src/main/java/com/baloise/confluence/digitalsignature/Signature.java#L178

For formatting, https://docs.atlassian.com/ConfluenceServer/javadoc/7.16.2/com/atlassian/confluence/core/ConfluenceActionSupport.html#getDateFormatter-- is used.  See also https://developer.atlassian.com/server/confluence/confluence-objects-accessible-from-velocity/#default-velocity-context 

"_Provides a date and time formatter suitable for the exporting user's locale and environment._"

🠖 Can you please **check your confluence date and time formats**, see https://confluence.atlassian.com/doc/configuring-time-and-date-formats-150144.html

To make sure that it is caused by the rendering, you can also export the signatures ( via the icon top right) and check the page source ( probably by pressing ctrl+U in your browser ).

You should see the timestamp of the export. Mine looks like
`<!-- generated Mar 10, 2022 10:18 -->` and changes every minute. I guess yours would also be minute = 9 anytime.

**Comment by MarkusTiede** [comment] 2022-03-10 12:10
@judithmerkel could you check whether the information provided by @culmat is helping with resolving your issue?

**Closed** 2022-04-25 08:27 UTC
Labels: bug
