### ISSUE TITLE
Timeout when I try to enable plugin

### ISSUE THREAD

**Issue by Mbeda** [baloise/digital-signature#32] opened 2018-10-11 20:03 UTC
`2018-10-11 15:51:59,757 WARN [http-nio-8090-exec-18] [confluence.util.profiling.DefaultActivityMonitor] close Exceeded the threshold of 60000 ms: ActivitySnapshot{startTime=1539287455351, threadId=180, threadName='http-nio-8090-exec-18', userId='[omitted]', type='web-request', summary='/rest/plugins/1.0/com.baloise.confluence.digital-signature-key'}
-- referer: https://ohsejiradev01.summit.network/confluence/plugins/servlet/upm | url: /confluence/rest/plugins/1.0/com.baloise.confluence.digital-signature-key | traceId: 489aa879176e0209 | userName: [omitted]
2018-10-11 15:51:55,651 ERROR [http-nio-8090-exec-18] [atlassian.plugin.manager.PluginEnabler] actualEnable Unable to start the following plugins due to timeout while waiting for plugin to enable: com.baloise.confluence.digital-signature
-- referer:[omitted]/confluence/plugins/servlet/upm | url: /confluence/rest/plugins/1.0/com.baloise.confluence.digital-signature-key | traceId: 489aa879176e0209 | userName: [omitted]
2018-10-11 15:51:55,625 ERROR [http-nio-8090-exec-18] [plugin.osgi.factory.OsgiPlugin] logAndClearOustandingDependencies Plugin 'com.baloise.confluence.digital-signature' never resolved service '&localNotificationService' with filter '(&(objectClass=com.atlassian.mywork.service.LocalNotificationService)(objectClass=com.atlassian.mywork.service.LocalNotificationService))'
2018-10-11 15:51:55,620 INFO [http-nio-8090-exec-18] [atlassian.plugin.manager.DefaultPluginManager] broadcastPluginDisabling Disabling com.baloise.confluence.digital-signature`

**Comment by MarkusTiede** [comment] 2018-10-15 13:17
Thanks for reporting!

@culmat : could you tell what might be causing this or do we need additional information?

**Comment by culmat** [comment] 2020-05-10 14:49
@Tiliavir I can not reproduce this. Let's close it?

**Comment by Tiliavir** [comment] 2020-05-11 04:46
@culmat : Yes, since there was no similar issue within the last year and since we cannot reproduce it, we might want to close it.

**Closed by Tiliavir** 2020-05-11 04:46 UTC
